version: "3.8"
services:
  sql:
    image: mysql
    environment:
      MYSQL_ALLOW_EMPTY_PASSWORD: "yes"
      MYSQL_HOST: "sql"
      MYSQL_DATABASE: "pokemonsdatabase"

    healthcheck:
      test: [ "CMD", "mysqladmin", "ping", "-h", "localhost" ]
      interval: 6s
      timeout: 3s
      retries: 100

  mongo:
    image: mongo

  server:
    build: .
    depends_on:
      sql:
        condition: service_healthy
      mongo:
        condition: service_started
    ports:
      - "8000:8000"
